export {
  ABOUT_SECTION_PAD as CONTACT_SECTION_PAD,
  ABOUT_BG_WHITE as CONTACT_BG_WHITE,
  ABOUT_BG_SURFACE as CONTACT_BG_SURFACE,
  ABOUT_INNER as CONTACT_INNER,
  ABOUT_HERO_SHELL as CONTACT_HERO_SHELL,
  ABOUT_HERO_CONTENT as CONTACT_HERO_CONTENT,
  ABOUT_HERO_BREADCRUMB as CONTACT_HERO_BREADCRUMB,
  ABOUT_HERO_BREADCRUMB_LIST as CONTACT_HERO_BREADCRUMB_LIST,
  ABOUT_BLOCK_SPACING as CONTACT_BLOCK_SPACING,
  ABOUT_GRID_GAP as CONTACT_GRID_GAP,
  ABOUT_CARD_GAP as CONTACT_CARD_GAP,
  ABOUT_PROSE as CONTACT_PROSE,
  ABOUT_PROSE_CENTER as CONTACT_PROSE_CENTER,
  ABOUT_HEADING_HERO as CONTACT_HEADING_HERO,
  ABOUT_HEADING_SECTION as CONTACT_HEADING_SECTION,
  ABOUT_HEADING_BLOCK as CONTACT_HEADING_BLOCK,
  ABOUT_BODY as CONTACT_BODY,
  ABOUT_BODY_SM as CONTACT_BODY_SM,
  ABOUT_CARD as CONTACT_CARD,
  ABOUT_CARD_HOVER as CONTACT_CARD_HOVER,
  ABOUT_IMAGE_FRAME as CONTACT_IMAGE_FRAME,
  CINEMATIC_IMAGE,
  ABOUT_BTN_ARROW as CONTACT_BTN_ARROW,
  ABOUT_BTN_MOBILE as CONTACT_BTN_MOBILE,
  ABOUT_FOCUS_RING as CONTACT_FOCUS_RING,
  ABOUT_FOCUS_RING_LIGHT as CONTACT_FOCUS_RING_LIGHT,
  ABOUT_TOUCH_TARGET as CONTACT_TOUCH_TARGET,
  ABOUT_ICON_BOX as CONTACT_ICON_BOX,
  ABOUT_ICON_STROKE as CONTACT_ICON_STROKE,
} from "@/components/sections/about/constants";

export const CONTACT_INPUT =
  "w-full rounded-[16px] border border-[#e8edf2] bg-[#fafbfd] px-4 py-3.5 text-sm text-[#1a2b4a] placeholder:text-[#94a3b8] transition-colors duration-[400ms] focus:border-engineering focus:bg-white focus:outline-none focus:ring-2 focus:ring-engineering/20 dark:border-border dark:bg-surface dark:text-foreground dark:focus:bg-card";

export const CONTACT_LABEL =
  "mb-2 block text-xs font-semibold tracking-[0.12em] text-[#5a6478] uppercase dark:text-foreground-muted";
