export {
  ABOUT_SECTION_PAD as PROJECTS_SECTION_PAD,
  ABOUT_BG_WHITE as PROJECTS_BG_WHITE,
  ABOUT_BG_SURFACE as PROJECTS_BG_SURFACE,
  ABOUT_INNER as PROJECTS_INNER,
  ABOUT_HERO_SHELL as PROJECTS_HERO_SHELL,
  ABOUT_HERO_SHELL_COMPACT as PROJECTS_HERO_SHELL_COMPACT,
  ABOUT_HERO_CONTENT as PROJECTS_HERO_CONTENT,
  ABOUT_HERO_BREADCRUMB as PROJECTS_HERO_BREADCRUMB,
  ABOUT_HERO_BREADCRUMB_LIST as PROJECTS_HERO_BREADCRUMB_LIST,
  ABOUT_BLOCK_SPACING as PROJECTS_BLOCK_SPACING,
  ABOUT_GRID_GAP as PROJECTS_GRID_GAP,
  ABOUT_CARD_GAP as PROJECTS_CARD_GAP,
  ABOUT_PROSE as PROJECTS_PROSE,
  ABOUT_PROSE_CENTER as PROJECTS_PROSE_CENTER,
  ABOUT_HEADING_HERO as PROJECTS_HEADING_HERO,
  ABOUT_HEADING_SECTION as PROJECTS_HEADING_SECTION,
  ABOUT_HEADING_BLOCK as PROJECTS_HEADING_BLOCK,
  ABOUT_BODY as PROJECTS_BODY,
  ABOUT_BODY_SM as PROJECTS_BODY_SM,
  ABOUT_CARD as PROJECTS_CARD,
  ABOUT_CARD_HOVER as PROJECTS_CARD_HOVER,
  ABOUT_IMAGE_FRAME as PROJECTS_IMAGE_FRAME,
  CINEMATIC_IMAGE,
  ABOUT_BTN_ARROW as PROJECTS_BTN_ARROW,
  ABOUT_BTN_MOBILE as PROJECTS_BTN_MOBILE,
  ABOUT_FOCUS_RING as PROJECTS_FOCUS_RING,
  ABOUT_FOCUS_RING_LIGHT as PROJECTS_FOCUS_RING_LIGHT,
  ABOUT_TOUCH_TARGET as PROJECTS_TOUCH_TARGET,
  ABOUT_ICON_BOX as PROJECTS_ICON_BOX,
  ABOUT_ICON_STROKE as PROJECTS_ICON_STROKE,
  ABOUT_TAB_PILL as PROJECTS_TAB_PILL,
  ABOUT_NAV_BTN as PROJECTS_NAV_BTN,
} from "@/components/sections/about/constants";

export const PROJECTS_INPUT =
  "w-full rounded-[16px] border border-[#e8edf2] bg-white px-4 py-3 text-sm text-[#1a2b4a] placeholder:text-[#94a3b8] transition-colors duration-[400ms] focus:border-engineering focus:outline-none focus:ring-2 focus:ring-engineering/20 dark:border-border dark:bg-card dark:text-foreground";

export const PROJECTS_SELECT =
  "rounded-[16px] border border-[#e8edf2] bg-white px-4 py-3 text-sm font-medium text-[#1a2b4a] transition-colors duration-[400ms] focus:border-engineering focus:outline-none focus:ring-2 focus:ring-engineering/20 dark:border-border dark:bg-card dark:text-foreground";
